import React, { useState, useEffect } from 'react';
import { useParams, Link } from 'react-router-dom';
import { 
  ArrowLeft, 
  Download, 
  FileText, 
  AlertTriangle, 
  Info, 
  Lightbulb, 
  CheckCircle2,
  Copy,
  Printer,
  Sparkles
} from 'lucide-react';
import { motion } from 'framer-motion';
import axios from 'axios';
import { toast } from 'react-hot-toast';

const DocumentEditor = () => {
  const { id } = useParams();
  const [doc, setDoc] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchDocument();
  }, [id]);

  const fetchDocument = async () => {
    try {
      const response = await axios.get(`http://localhost:8000/documents/${id}`);
      setDoc(response.data);
    } catch (error) {
      toast.error('Failed to load document');
    } finally {
      setLoading(false);
    }
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(doc.content);
    toast.success('Content copied to clipboard');
  };

  if (loading) return (
    <div className="h-[60vh] flex items-center justify-center">
      <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-primary-600"></div>
    </div>
  );

  if (!doc) return <div>Document not found.</div>;

  return (
    <div className="max-w-7xl mx-auto space-y-8">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div className="flex items-center gap-4">
          <Link to="/generator" className="p-2 hover:bg-slate-100 rounded-lg transition-colors">
            <ArrowLeft size={20} />
          </Link>
          <div>
            <h1 className="text-2xl font-bold text-slate-900">{doc.title}</h1>
            <p className="text-sm text-slate-500">Generated on {new Date(doc.created_at).toLocaleDateString()}</p>
          </div>
        </div>
        <div className="flex gap-3">
          <button onClick={copyToClipboard} className="bg-white border border-slate-200 text-slate-700 px-4 py-2 rounded-xl font-semibold flex items-center gap-2 hover:bg-slate-50 transition-all">
            <Copy size={18} /> Copy
          </button>
          <button className="bg-slate-900 text-white px-5 py-2.5 rounded-xl font-semibold flex items-center gap-2 hover:bg-slate-800 transition-all shadow-md">
            <Download size={18} /> Export PDF
          </button>
        </div>
      </div>

      <div className="grid lg:grid-cols-3 gap-8">
        {/* Document Preview */}
        <div className="lg:col-span-2 space-y-6">
          <div className="glass-card p-10 min-h-[800px] shadow-xl relative overflow-hidden bg-white">
            <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-primary-600 to-indigo-600" />
            <div className="prose prose-slate max-w-none">
              <div className="whitespace-pre-wrap font-serif text-slate-800 leading-relaxed text-lg">
                {doc.content}
              </div>
            </div>
            
            <div className="mt-20 pt-8 border-t border-slate-100 text-center">
              <p className="text-xs text-slate-400 italic">
                This document is a draft generated by ClauseGuard AI. Please consult with a legal professional.
              </p>
            </div>
          </div>
        </div>

        {/* AI Recommendations Sidebar */}
        <div className="space-y-6">
          <div className="glass-card p-6 bg-amber-50/50 border-amber-200">
            <h3 className="text-lg font-bold text-amber-900 flex items-center gap-2 mb-4">
              <AlertTriangle className="text-amber-600" size={20} />
              Important Notice
            </h3>
            <p className="text-sm text-amber-800 leading-relaxed">
              This is an AI-assisted draft. While it covers major standard points, every business is unique. We strongly recommend a final review by a lawyer.
            </p>
          </div>

          <div className="space-y-4">
            <h3 className="text-lg font-bold text-slate-900 flex items-center gap-2 px-1">
              <Sparkles className="text-primary-600" size={20} />
              AI Recommendations
            </h3>
            
            {doc.recommendations && doc.recommendations.map((rec, i) => (
              <motion.div 
                initial={{ opacity: 0, x: 20 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: i * 0.1 }}
                key={i}
                className={`p-4 rounded-2xl border-l-4 flex gap-4 ${
                  rec.type === 'critical' ? 'bg-red-50 border-red-500' : 
                  rec.type === 'warning' ? 'bg-amber-50 border-amber-500' : 'bg-blue-50 border-blue-500'
                }`}
              >
                <div className={`mt-0.5 ${
                  rec.type === 'critical' ? 'text-red-600' : 
                  rec.type === 'warning' ? 'text-amber-600' : 'text-blue-600'
                }`}>
                  {rec.type === 'critical' ? <AlertTriangle size={20} /> : 
                   rec.type === 'warning' ? <Info size={20} /> : <Lightbulb size={20} />}
                </div>
                <div>
                  <h4 className={`text-sm font-bold ${
                    rec.type === 'critical' ? 'text-red-900' : 
                    rec.type === 'warning' ? 'text-amber-900' : 'text-blue-900'
                  } mb-1`}>
                    {rec.type.toUpperCase()}
                  </h4>
                  <p className="text-sm text-slate-700">{rec.text}</p>
                </div>
              </motion.div>
            ))}

            {!doc.recommendations?.length && (
              <div className="p-4 bg-slate-50 border border-slate-100 rounded-2xl text-center text-slate-500 text-sm italic">
                No specific recommendations for this draft.
              </div>
            )}
          </div>

          <div className="glass-card p-6">
            <h3 className="text-sm font-bold text-slate-900 mb-4 uppercase tracking-widest">Next Steps</h3>
            <ul className="space-y-3">
              {[
                'Review the generated text',
                'Consult with a legal expert',
                'Download the PDF version',
                'Upload your final signed copy'
              ].map((step, i) => (
                <li key={i} className="flex items-center gap-3 text-sm text-slate-600">
                  <div className="w-5 h-5 bg-green-100 text-green-600 rounded-full flex items-center justify-center flex-shrink-0">
                    <CheckCircle2 size={12} />
                  </div>
                  {step}
                </li>
              ))}
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
};

export default DocumentEditor;
